const views=[...document.querySelectorAll('.view')],tabs=[...document.querySelectorAll('.tabs button')];
function showView(id){views.forEach(v=>v.classList.toggle('active',v.id===id));tabs.forEach(t=>t.classList.toggle('active',t.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
tabs.forEach(t=>t.onclick=()=>showView(t.dataset.view));document.getElementById('startBtn').onclick=()=>showView('sun');
const sunQ=[{q:'The Sun is a star.',a:true},{q:'The Sun is smaller than Earth.',a:false},{q:'The Sun rotates on its axis.',a:true},{q:'The Sun is a solid sphere.',a:false},{q:'The Sun provides light and heat to Earth.',a:true}];let curSun=null,score=0;
sunNext.onclick=()=>{curSun=sunQ[Math.floor(Math.random()*sunQ.length)];sunQuestion.textContent=curSun.q;sunFeedback.textContent=''};
document.querySelectorAll('[data-sun]').forEach(b=>b.onclick=()=>{if(!curSun)return;let ok=(b.dataset.sun==='true')===curSun.a;if(ok)score++;sunScore.textContent=score;sunFeedback.textContent=ok?'Correct! ⭐':'Try again.'});
const moon=[{clue:"Earth's natural satellite",color:'red'},{clue:'A hollow on the Moon’s surface',color:'yellow'},{clue:'Movement around its own axis',color:'green'},{clue:'Movement of the Moon around Earth',color:'blue'},{clue:'The Moon reflects sunlight',color:'orange'},{clue:'The area where craters are found',color:'darkblue'}];let curMoon=null;
moonNext.onclick=()=>{curMoon=moon[Math.floor(Math.random()*moon.length)];moonClue.textContent=curMoon.clue;moonFeedback.textContent=''};
document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{if(!curMoon)return;moonFeedback.textContent=b.dataset.color===curMoon.color?'Correct colour! 🌙':'Try another colour.'});
const safe=[{s:'A stranger asks you to send your photo.',a:'blue'},{s:'A shocking news item has no clear source.',a:'yellow'},{s:'A website asks for your home address.',a:'blue'},{s:'A classmate shares another student’s photo without permission.',a:'orange'},{s:'A pop-up says “You won a prize! Click now!”',a:'red'},{s:'An online message scares you.',a:'darkblue'}];let curSafe=null;
safeNext.onclick=()=>{curSafe=safe[Math.floor(Math.random()*safe.length)];safeScenario.textContent=curSafe.s;safeFeedback.textContent=''};
document.querySelectorAll('[data-safe]').forEach(b=>b.onclick=()=>{if(!curSafe)return;safeFeedback.textContent=b.dataset.safe===curSafe.a?'Good choice! ✅':'Think again.'});
const colors=['Red','Orange','Yellow','Green','Blue','Dark Blue'];
document.querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>{let team=b.dataset.team;teamEditor.classList.remove('hidden');teamTitle.textContent='Team '+team;factFields.innerHTML=colors.map((c,i)=>`<div class="fact-row"><strong>${c}</strong><input id="fact${i}" placeholder="Write a short scientific fact"></div>`).join('');saveTeam.dataset.team=team});
saveTeam.onclick=e=>{let team=e.target.dataset.team;let facts=colors.map((_,i)=>document.getElementById('fact'+i)?.value||'');localStorage.setItem('team-'+team,JSON.stringify(facts));saveMsg.textContent='Saved on this device.'};
let timerInt=null;timerBtn.onclick=()=>{clearInterval(timerInt);let n=60;timer.textContent=n;timerInt=setInterval(()=>{n--;timer.textContent=n;if(n<=0){clearInterval(timerInt);timer.textContent='Time! 🎉'}},1000)};
